### PR TITLE
Add missing inhertance to _Schema for _StructSchema.

### PR DESCRIPTION
**Pull request by litghost**
I believe _StructSchema should be inheriting from _Schema per: https://github.com/capnproto/capnproto/blob/659507a358e4b7aa6314011375f20e8dc5abdaa6/c%2B%2B/src/capnp/schema.h#L239

I noticed that _StructSchema was missing a method that _ParsedSchema had (get_proto), which is because _ParsedSchema is marked as inheriting from _Schema: https://github.com/capnproto/pycapnp/blob/a4ef16e831a45e532aca9f4418971645805cafc1/capnp/lib/capnp.pyx#L2922

### CODE REVIEW

**Comment by haata** [comment]
I'll have to look more closely, the CI is blowing up so there's something Cython doesn't like.

**Comment by litghost** [comment]
> I'll have to look more closely, the CI is blowing up so there's something Cython doesn't like.

I'm working on a fix.  This is more complicated than I initially expected, but I think I know what to do.

**Comment by litghost** [comment]
> > I'll have to look more closely, the CI is blowing up so there's something Cython doesn't like.
> 
> I'm working on a fix. This is more complicated than I initially expected, but I think I know what to do.

Fix is in, let's see if the CI passes.

**Comment by litghost** [comment]
> > > I'll have to look more closely, the CI is blowing up so there's something Cython doesn't like.
> > 
> > 
> > I'm working on a fix. This is more complicated than I initially expected, but I think I know what to do.
> 
> Fix is in, let's see if the CI passes.

CI is green!  Take another look.

**Review by haata — APPROVED** [review]

**Comment by haata** [comment]
LGTM!

**Pull request merged**
