### PR TITLE
Build for capnp 0.7.0

### PR DESCRIPTION
**Pull request by jrouviere**
Hello,
That's not my code, but I realised I needed the fork from @afonso360 to build with the latest capnp release (with clang on macos).
I think that would be worth merging in the main repo.

### CODE REVIEW

**Comment by de-vri-es** [comment]
This also works on Arch Linux, whereas current `develop` does not compile.

**Comment by ramajd** [comment]
is there any plan to release a version based on CapnProto 0.7.0 ?

**Comment by jrouviere** [comment]
@cjermain I'll try to find some time, but I don't really have a project using pycapnp at the moment, so I might not be the best person to test. I also don't have write access on the original fork so would need to create a new PR.

**Comment by de-vri-es** [comment]
@jrouviere: is this no longer relevant? I didn't see any changes to master for 0.7.0 support :o

**Comment by jrouviere** [comment]
Ha, sorry, I'm not working on any project involving capnp at the moment. I just tried running `pip install pycapnp` on my machine and it seemed to have worked so I assumed the problem was fixed.

**Comment by de-vri-es** [comment]
hmm, you might be on a distro that still uses 0.6.0? For me it's still broken.

**Comment by de-vri-es** [comment]
sorry, I was having unrelated issues apparently. In a clean environment on Arch, it builds properly indeed. Although I'm a bit confused as to why, since nothing changed here?

**Pull request closed without merging**
