### PR TITLE
Add Python 3.11 to Github Actions builds

### PR DESCRIPTION
**Pull request by msachtler**
This adds cp311 to the Github actions to produce wheels for Python 3.11 for aarch64 and x86_64.

The manylinux2010 images are EOL and don't support 3.11, so I removed those builds in favor of the 2014 variant. To actually get the i686 artifact to build under manylinux2014, I also had to bump the bundled capnp version from 0.8.1 to 0.10.3 (the most recent version right now).

### CODE REVIEW

**Comment by haata** [comment]
Hmm, since manylinux2010 is now EOL (https://discuss.python.org/t/dropping-manylinux2010-docker-images-support-in-2022/13540), maybe the better solution here is to just drop manylinux2010 entirely?

**Comment by msachtler** [comment]
Happy to rip it out, but I'm not sure how difficult it would be to get i686 building on manylinux2014.

This is the specific error I got when I tried it:
```
/ws/bundled/capnproto-c++/src/kj/filesystem-disk-unix.c++: In lambda function:
/ws/bundled/capnproto-c++/src/kj/filesystem-disk-unix.c++:1098:40: error: ‘SYS_renameat2’ was not declared in this scope; did you mean ‘SYS_renameat’?
 1098 |       KJ_SYSCALL_HANDLE_ERRORS(syscall(SYS_renameat2,
      |                                        ^~~~~~~~~~~~~
/ws/bundled/capnproto-c++/src/kj/filesystem-disk-unix.c++: In lambda function:
/ws/bundled/capnproto-c++/src/kj/filesystem-disk-unix.c++:1127:40: error: ‘SYS_renameat2’ was not declared in this scope; did you mean ‘SYS_renameat’?
 1127 |       KJ_SYSCALL_HANDLE_ERRORS(syscall(SYS_renameat2,
      |                                        ^~~~~~~~~~~~~
gmake[2]: *** [src/kj/CMakeFiles/kj.dir/filesystem-disk-unix.c++.o] Error 1
gmake[1]: *** [src/kj/CMakeFiles/kj.dir/all] Error 2
gmake: *** [all] Error 2
```

**Comment by kentonv** [comment]
That's weird, that code is guarded by:

```
#if __linux__ && defined(RENAME_EXCHANGE) && defined(SYS_renameat2)
```

See: https://github.com/capnproto/capnproto/blob/931074914eda9ca574b5c24d1169c0f7a5156594/c%2B%2B/src/kj/filesystem-disk-unix.c%2B%2B#L1099-L1110

So if `SYS_renameat2` is not defined the code should not be compiled at all...

**Comment by kentonv** [comment]
Oh, the `&& defined(SYS_renameat2)` was added in version 0.10 of capnproto-c++:

https://github.com/capnproto/capnproto/commit/172090e24f3e515f8997c60bb9bb0dc41126bbaf

Are you trying to use an older version?

**Comment by msachtler** [comment]
I think it built with the bundled version, which https://github.com/capnproto/pycapnp/blob/master/buildutils/bundle.py#L29 appears to be 0.8.1. I can try to bump that version forward and see how it does!

**Comment by msachtler** [comment]
Okay, thanks for the pointer on the version update. In the commits I just pushed, I added i686 to the manylinux2014 build and fully deleted the 2010 version. This also updates the bundled version to 0.10.3.

In my fork, all the CI builds passed. I did a few spot-checks by downloading the built wheel artifacts, and installed the arm64 mac wheel (natively on my laptop), and tested the arm64, x86_64, and i686 linux wheels in docker containers. I didn't do any extensive testing, just made sure they could install and that i could then `import capnp`.

**Comment by haata** [comment]
Excellent, once the CI is passing here I'll merge it in.
Given that we also needed to upgrade the base capnproto to 0.10 it's probably best to bump the version to 1.3.0 as well.

**Comment by msachtler** [comment]
Yeah, that makes sense. Is that something I should add to this PR, or does that happen separately? 

Thanks for the quick turnaround on the review here!

**Comment by haata** [comment]
Nah, I can handle that. Should be ready in a day or so.

**Comment by haata** [comment]
Done! https://pypi.org/project/pycapnp/1.3.0/

**Pull request merged**
