### PR TITLE
Replacing end-of-life Python versions with live versions

### PR DESCRIPTION
**Pull request by cjermain**
This PR removes support for Python versions that have reached end-of-life (EOL). It replaces them with live versions that are supported. Since `setuptools` specifically drops support for EOL versions, these versions cause errors in the continuous integration (CI) tests -- #175 fails CI for this reason.

Python 2.6 - [EOL 2013-10-29](https://www.python.org/dev/peps/pep-0361/#release-lifespan)
Python 3.2 - [EOL 2016-02-20](https://www.python.org/dev/peps/pep-0392/#lifespan)
Python 3.3 - [EOL 2017-09-29](https://www.python.org/dev/peps/pep-0398/#lifespan)

### CODE REVIEW

**Comment by cjermain** [comment]
[Travis CI currently has poor support for Python 3.7](https://github.com/travis-ci/travis-ci/issues/9815). I've added a patch for this version.

**Comment by cjermain** [comment]
While Travis CI supports Python 3.7 in Xenial machines, there are 2 issues.
1. Xenial machines do not support PyPy in the current configuration.
2. Cython 0.21.2 does not work well with Python 3.7.

I suggest a future PR tackles updating the Cython version to work better with Python 3.7, and addresses the support for PyPy.

This PR is ready for review.

**Comment by cjermain** [comment]
@kentonv, what is the status of this repo? It looks like the last commit was 12 months ago.

**Comment by kentonv** [comment]
Unfortunately, the previous maintainer has moved on, so this repo is now unmaintained. :/

If someone wants to take it over, let me know.

**Comment by cjermain** [comment]
@kentonv, I'm happy to put in a little work to keep the CI alive, and help with reviews. I don't have the bandwidth to be a full maintainer though.

**Comment by kentonv** [comment]
Hey @jparyani, is it OK with you if I assign new owners to this repo?

(I've also e-mailed him in case he doesn't check here.)

**Comment by cjermain** [comment]
@kentonv, I would like commit access to address some of the outstanding issues. As I mentioned, I don't have the bandwidth to be a full maintainer -- so we should also keep looking for more folks who are interested to get involved.

**Comment by kentonv** [comment]
@cjermain Sorry this fell off my radar over the holidays. I've given you write acccess. Thanks for offering to help!

**Comment by cjermain** [comment]
Thanks @kentonv!

**Pull request merged**
